name: Earthly
description: Install earthly CLI named earth from https://github.com/earthly/earthly/releases
inputs:
  version:
    default: v0.3.8 # earthly/earthly
    required: false
    description: Version of earthly CLI to install (defaults to latest)
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -ux
        mkdir -m 0755 -p ~/bin/
        curl -Lo ~/bin/earth https://github.com/earthly/earthly/releases/download/"${{inputs.version}}"/earth-"$(uname -s | tr '[:upper:]' '[:lower:]')"-amd64
        chmod 555 ~/bin/earth
        echo '::add-path::~/bin/'
