name: kustomize
description: Install kustomize from https://github.com/kubernetes-sigs/kustomize/releases
inputs:
  version:
    default: kustomize/v3.8.1 # kubernetes-sigs/kustomize
    required: false
    description: Version of kustomize to install (defaults to latest)
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        VERSION=$(echo '${{inputs.version}}' | sed 's|^kustomize/||')
        set -ux
        mkdir -m 0755 -p ~/bin/
        curl -LO https://github.com/kubernetes-sigs/kustomize/releases/download/'${{inputs.version}}'/kustomize_"$VERSION"_linux_amd64.tar.gz
        tar --no-same-{o,p} -C ~/bin/ -xf kustomize_"$VERSION"_linux_amd64.tar.gz kustomize
        chmod 555 ~/bin/kustomize
        rm kustomize_"$VERSION"_linux_amd64.tar.gz
        echo '::add-path::~/bin/'
