name: k3d
description: Install k3d from https://github.com/rancher/k3d/releases
inputs:
  version:
    default: v3.1.2 # rancher/k3d
    required: false
    description: Version of k3d to install (defaults to latest)
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -ux
        mkdir -m 0755 -p ~/bin/
        curl -Lo ~/bin/k3d https://github.com/rancher/k3d/releases/download/'${{inputs.version}}'/k3d-"$(uname -s | tr '[:upper:]' '[:lower:]')"-amd64
        chmod 555 ~/bin/k3d
        echo '::add-path::~/bin/'
