name: Test Conftest

on:
  push:
    paths:
      - .github/workflows/conftest.yaml
      - conftest/**
  pull_request:
    paths:
      - .github/workflows/conftest.yaml
      - conftest/**

jobs:
  Test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
      - name: Use ${{github.repository}}/conftest
        uses: ./conftest
      - run: conftest --version
