name: Test Conftest

on:
  push:
    paths:
      - .github/workflows/conftest.yaml
      - conftest/**
  pull_request:
    paths:
      - .github/workflows/conftest.yaml
      - conftest/**

jobs:
  Test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2
      - name: Use ${{github.repository}}/conftest
        uses: ./conftest
      - run: conftest --version
