name: Test k3d

on:
  push:
    paths:
      - .github/workflows/k3d.yaml
      - k3d/**
  pull_request:
    paths:
      - .github/workflows/k3d.yaml
      - k3d/**

jobs:
  Test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
      - name: Use ${{github.repository}}/k3d
        uses: ./k3d
      - run: k3d --version
