name: Test kustomize

on:
  push:
    paths:
      - .github/workflows/kustomize.yaml
      - kustomize/**
  pull_request:
    paths:
      - .github/workflows/kustomize.yaml
      - kustomize/**

jobs:
  Test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2
      - name: Use ${{github.repository}}/kustomize
        uses: ./kustomize
      - run: kustomize version --short
