name: Test OPA

on:
  push:
    paths:
      - .github/workflows/opa.yaml
      - opa/**
  pull_request:
    paths:
      - .github/workflows/opa.yaml
      - opa/**

jobs:
  Test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
      - name: Use ${{github.repository}}/opa
        uses: ./opa
      - run: opa version
